### ISSUE TITLE
Proposal: extract all Iris support to another repository

### ISSUE THREAD

**Issue by colega** [coopernurse/barrister-go#4]
I think this repository will be cleaner and clearer if all Iris-related stuff was extracted to an external repository, like `barrister-go-iris`. Iris support is completely decoupled from the main logic of `barrister-go` package and it only makes support more complex as you need to install those packages in order to run a simple `go test ./...`

**Comment by coopernurse** [comment]
Tell me more about why you're running `go test ./...`  - there's only one exported package.  This appears to work with the sources in master:

```
[james@robotron barrister-go]$ go get github.com/couchbaselabs/go.assert
[james@robotron barrister-go]$ go test
PASS
ok  	_/home/james/src/barrister/barrister-go	0.007s
```

The `test.sh` script also appears to still work

**Comment by coopernurse** [comment]
I'll push a note to the README to clarify how to run the tests.
